source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'TTGEmojiRate_Example', :exclusive => true do
  pod "TTGEmojiRate", :path => "../"
end

target 'TTGEmojiRate_Tests', :exclusive => true do
  pod "TTGEmojiRate", :path => "../"

  
end
