platform :ios, '16.0'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false
use_frameworks!

target 'TTGEmojiRate_Example' do
    pod 'TTGEmojiRate', :path => '../'

    target 'TTGEmojiRate_Tests' do
        inherit! :search_paths

    end
end
