platform :ios, '8.0'
use_frameworks!

target 'TTGEmojiRate_Example' do
    pod 'TTGEmojiRate', :path => '../'
    
    target 'TTGEmojiRate_Tests' do
        inherit! :search_paths
        
    end
end